Neuen Ort Erding einfügen
SanJSp/lets_git_reisefuehrer pull request #23
Opened 2020-06-26 12:43 UTC by lothar8ew

Bin das erste Mal dabei und daher noch unsicher. Repo geforked, ergänzt und gepushed. Mal sehen, was ich noch überlesen habe. Meine vielen Commits kamen dadurch zustande, dass ich Markdown nicht kannte ...

2020-06-26 14:45 UTC, SanJSp requested changes
Bitte die Bearbeitung von dem Issue Tempalte rückgängig machen

2020-06-26 14:45 UTC, SanJSp commented on .github/ISSUE_TEMPLATE/neuen-ort-anfragen.md
> +Wenn dieser Issue funktioniert, erstelle ich einen Pull Request, der Branch ist fertig.
Diese Änderungen sollten nicht enthalten sein.

2020-06-26 16:29 UTC, lothar8ew commented on .github/ISSUE_TEMPLATE/neuen-ort-anfragen.md
> +Wenn dieser Issue funktioniert, erstelle ich einen Pull Request, der Branch ist fertig.
Ich hoffe, das hat geklappt. Ich schwimme da noch etwas, was ich von wo aus ändern soll ...

2020-06-26 20:58 UTC, Jannik-R requested changes
Ich finde die Seite gut gelungen. 
Allerdings würde ich darum bitten, die Bilddatei in den gleichen Ordner wie die .md Datei zu verschieben. Diese liegt zur Zeit im Hauptverzeichnis. 

Hierzu läuft zur Zeit aber auch ein Issue (#28) 
Eventuell wird das Bild dann später noch mal verschoben. - Das würde ich dann aber machen, wenn wir uns auf eine Möglichkeit geeinigt haben.

2020-06-26 21:49 UTC, lothar8ew commented
Habe die Changes vollzogen. Ist es damit erledigt oder muss ich am Pull Request nochmals was tun?
Oder neuen Pull Request?
(Lauter  Anfängerfragen für die ich keine Antworten in den FAQs finde).

2020-06-26 22:26 UTC, Jannik-R requested changes
Das Bild ist zur Zeit noch im Hauptverzeichnis vorhanden und muss noch aus dem Git gelöscht werden. 
(Nur in der Ordnerstruktur löschen bewirkt nicht, dass die Datei auch bei Git gelöscht wird.)

2020-06-26 22:26 UTC, Jannik-R commented on Europa/Deutschland/Erding.md
> +![Hier kommt ein png rein!](/Erding2009.png)
Hier müsste dann noch der Link angepasst werden.

2020-06-26 22:28 UTC, Jannik-R commented
> Habe die Changes vollzogen. Ist es damit erledigt oder muss ich am Pull Request nochmals was tun?
> Oder neuen Pull Request?
> (Lauter Anfängerfragen für die ich keine Antworten in den FAQs finde).

Änderungen, die du auf den entsprechenden Branch pusht werden automatisch im Pull Request aufgenommen. 
Du musst also wenn du Änderungen vornimmst nichts weiter am Pull Request machen. (Außer eventuell auf Kommentare zu antworten)

2020-06-26 23:48 UTC, lothar8ew commented
Danke für die Infos, war hilfreich. Bilddatei im Hauptverzeichnis deleted. Ich glaube, momentan stimmt alles.
Lothar

2020-06-27 00:06 UTC, Jannik-R approved these changes
Für mich sieht alles gut aus

2020-06-29 04:05 UTC, merged