Stadt thun
SanJSp/lets_git_reisefuehrer pull request #45
Opened 2020-06-29 14:34 UTC by PeterGyger

Beschreibung der Stadt Thun. Mit Fotos.
Im Verzeichnis Schweiz (unterhalb Europa).

2020-06-29 21:48 UTC, Jannik-R requested changes
Werden die Bilder, die bisher nicht eingebunden sind noch eingebunden? 

Und die Datei "gh-branch.png" scheint hier versehentlich mit reingerutscht zu seien.

2020-06-29 21:48 UTC, Jannik-R commented on Europa/Schweiz/thun/Thun.md
> +![Wappen Thun](/Europa/Schweiz/kt_bern/thun/thun.png)
Hier muss der Link noch abgeändert werden.

2020-06-30 06:32 UTC, PeterGyger commented
gh-branch.png ist lokal nicht im Verzeichnis mit diesem Repository. Woher soll die Datei kommen?
Bilder sind eingebunden, wenn auch nicht zwingend verlangt
Kann ich den Pfad direkt hier anpassen oder lösche ich den PR und schicke nochmals

2020-06-30 20:44 UTC, Jannik-R commented
Wenn du einfach nochmal auf deinen Branch pusht, dann wird das hier mit aufgenommen. 
Die Datei steht unter Files changed aufgelistet. 
Daher scheint diese irgendwann mit in deinen Branch geraten zu sein. 
Du kannst diese aber auch einfach per Commit entfernen.

2020-07-01 06:48 UTC, PeterGyger commented
Done

2020-07-02 19:57 UTC, Jannik-R approved these changes

2020-07-02 19:57 UTC, merged